name: PROJECT-NAME
recipe: drupal9

config:

  webroot: web
  via: nginx
  drush: false

services:

  appserver:
    build:
      - composer install

  node:
    type: node

tooling:

  drush:
    service: appserver
    cmd:
      - vendor/bin/drush

  phpunit:
    service: appserver
    cmd:
      - vendor/bin/phpunit -c ./phpunit.xml

  node:
    service: node

  npm:
    service: node
