name: test-site
recipe: drupal9

config:

  webroot: web
  drush: false

services:

  appserver:
    build:
      - composer install

  node:
    type: node

  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

proxy:

  mailhog:
    - mail.test-site.lndo.site

tooling:

  drush:
    service: appserver
    cmd:
      - vendor/bin/drush

  phpunit:
    service: appserver
    cmd:
      - vendor/bin/phpunit -c ./phpunit.xml

  node:
    service: node

  npm:
    service: node
